### ISSUE TITLE
Update release note generation to tag participants

### ISSUE THREAD

**Issue by gsidebo** [mitodl/release-script#11]
Currently, the generated release candidate PR's (eg: https://github.com/mitodl/micromasters/pull/569) refer to participants by name. If possible, we should @ mention these participants so they are automatically notified about the release candidate PR

**Comment by pdpinch** [comment]
This idea came up again in our 3/3 retrospective: https://github.mit.edu/odl-engineering/retrospectives/issues/7

**Comment by j2tausig** [comment]
Can you guys unsubscribe me from your github please?

Thanks.

Jared

**Comment by pdpinch** [comment]
Sorry about that Jared. I can't find your name *anywhere* on our github.com/mitodl organization. I have no idea why you would get a notification, particularly for this repo.

**Comment by j2tausig** [comment]
Sadly, I no longer have access to the 2-way authenticator, so I have no way
to
mute the thread on my end.

:(

Jared

**Comment by noisecapella** [comment]
The release notes are generated from the git commit information which doesn't necessarily contain the username of the commiter. We could add some fixed lookup of email to github username to work around this

**Comment by pdpinch** [comment]
This appears to be working now.
