### ISSUE TITLE
write a date to the release notes

### ISSUE THREAD

**Issue by pdpinch** [mitodl/release-script#158]
Now that we're doing so many releases, it can be hard to trace back a change in app behavior to a specific release. It would be nice to have (human-readable) dates in the release notes to help. 

Ideally we'd record the date and time of the production release. Could we update the release notes at the time the release is merged back into master?

As a one-time activity, it would be nice to retroactively record the dates of each release's tag as well.

**Comment by mbertrand** [comment]
@pdpinch is this formatting acceptable?

<img width="579" alt="screen shot 2018-07-11 at 2 54 37 pm" src="https://user-images.githubusercontent.com/187676/42593464-82483d78-851a-11e8-93b1-ee7e317a2c94.png">

**Comment by pdpinch** [comment]
Is there a canned format that's close to `(Released July 11, 2018)` -- it's just easier to read and we don't need the time.

**Comment by Ferdi** [comment]
Or maybe we need the version nr too ?

Version 0.36.1 (July 11, 2018)
