### ISSUE TITLE
Add confirmation message on certain Doof buttons

### ISSUE THREAD

**Issue by noisecapella** [mitodl/release-script#198]
See https://api.slack.com/docs/message-buttons

**Comment by noisecapella** [comment]
@rhysyngsun Sorry, I should have written down the context here. I think I discussed this with you. Which buttons should have confirmation messages?

**Comment by rhysyngsun** [comment]
@noisecapella i think definitely the button to release to production should have a confirmation. My accidental click over the holidays was because the mobile app was acting sluggish caused a mis-click. A confirmation would've saved that.
