### ISSUE TITLE
verify availability of required programs

### ISSUE THREAD

**Issue by pwilkins** [mitodl/release-script#3]
The script expects some programs to be in the path.  The script will fail if these programs won't run. This issue is about testing for these programs' availability and the graceful recovery if they are unavailable.  It does not require the list of programs to be complete for resolution.

The programs are:
- git
- hub
- perl
- awk

With the exception of ``hub``, these programs exist by default on most developer's machines.

**Comment by Ferdi** [comment]
Not sure what you are trying to do but can it be written in python only ?

**Comment by noisecapella** [comment]
I agree, python is available in many default installs and keeping it python only would make things cleaner

**Comment by pwilkins** [comment]
Am I correct in understanding these comments as a rejection of ``bash`` scripting as the way we automate the release process?

**Comment by justinabrahms** [comment]
I really disagree here. Dealing with shell processes in python is a giant pain in the ass. Dealing with output redirection is similarly painful.

Bash is an extremely fundamental tool that allows for iterative development. The features we're using have been around for.. 30 years?  Not to mention everyone on the team uses bash daily.

The step from "peter types in a bunch of commands manually" to the next best thing isn't to dive into the subprocess module. It's to put them into an executable format. Bash is the best way to do that, imo.

**Comment by pwilkins** [comment]
I acknowledge the goal of "keeping things cleaner" as @noisecapella so aptly put it.  At the same time, I'm aware that the solution should fit the problem.  
The process we're trying to automate is a series of command line steps.  It's easier to conceptualize the solution on the command line as well.  I imagine that doing these steps in Python will abstract them into multiple lines of code that won't be cleaner than a ``bash`` script.

**Comment by noisecapella** [comment]
It depends how complicated the scripts get. Error handling is not the default in bash and things like functions and arrays are difficult to work with by comparison. I don't have a strong opinion against bash here, but if we do use bash we should read this first: https://sipb.mit.edu/doc/safe-shell/

In summary, we should use the `set -euf -o pipefail` command at the top of the file (maybe except the globbing part) and quote every variable. This isn't just a security precaution, it also make it much easier to diagnose what went wrong.

**Comment by justinabrahms** [comment]
:+1: for following the style guide things George suggested. That looks like a pretty solid flag to set. :)

**Comment by pwilkins** [comment]
Fixed by #1
