### ISSUE TITLE
Run bot in a dedicated server

### ISSUE THREAD

**Issue by noisecapella** [mitodl/release-script#37]
We can use tornado to integrate the bot's existing asyncio loop with a minimal web server to handle Slack POST requests, which would allow us to have interactivity with the Slack bot

**Comment by noisecapella** [comment]
@blarghmatey @shaidar Is there time to get an EC2 instance running this week? I'm happy to do the deployment part myself

**Comment by pdpinch** [comment]
Does heroku not work? 

----------------
I am mobile.

**Comment by noisecapella** [comment]
Heroku's fine with me if it works for everyone else. It needs to run continously so I think it would be a Hobby dyno which is $7 a month, not sure how EC2 compares

**Comment by noisecapella** [comment]
@blarghmatey @shaidar @pdpinch Does anyone mind if I just set up a heroku instance myself for this?

**Comment by pdpinch** [comment]
I don't mind. But MIT should pay for it.

**Comment by blarghmatey** [comment]
I created an app for the bot and added @noisecapella to it

**Comment by noisecapella** [comment]
Thanks, I added #86 to do configuration. I think we can close this now
