### ISSUE TITLE
Support more project types (beside Django projects)

### ISSUE THREAD

**Issue by pwilkins** [mitodl/release-script#5]
The script currently expects to find the version number in `settings.py`, a file that usually only exists in Django projects.  This change would check additional well-known locations for the version number, for example,  `setup.py`.  This would allow the script to be used for more projects.

**Comment by justinabrahms** [comment]
Do we have other projects we'd like to use this on yet?

**Comment by pdpinch** [comment]
- pylmod (python library)
- lmod_proxy (flask app)

**Comment by justinabrahms** [comment]
Cool.

We already handle setup.py. We can make this function a bit smarter:
https://github.com/mitodl/release-script/blob/master/release.sh#L97 to look
for more version identifiers or files?

**Comment by pwilkins** [comment]
I'd prefer the script looks for version numbers and fails if the collected version numbers aren't all the same.  I've found inconsistent version numbers more than once.

**Comment by noisecapella** [comment]
I think this is handled properly at the moment, we'll may need to modify for future projects
