### ISSUE TITLE
Support both .md and .rst formatted RELEASE.xx content

### ISSUE THREAD

**Issue by pwilkins** [mitodl/release-script#8]
At one time, our practice was to format documentation using ReStructuredText markup.  We now seem to be using Markdown.  The release-script formats `RELEASE.rst` as rst.  If our practice now is to use Markdown, the release script should follow this practice.  

Note: Github renders both formats, so this is only a nice-to-have.

**Comment by noisecapella** [comment]
I think we've standardized on RELEASE.rst for the time being
